### ISSUE TITLE
After scraping https://getbootstrap.com , having problem rendering

### ISSUE THREAD

**Issue by guruprasaad123** [Skallwar/suckit#86] opened 2020-05-24 16:59 UTC
# my first Experiment :

I tasked **suckit** to scrape the website - https://getbootstrap.com so that i can have bootstrap documentations offline it seems to have downloaded the website but i opened the website in my browser it isn't rendering properly ( having issues with css files i guess )

And this Added feature to **suckit**

**Comment by CohenArthur** [comment] 2020-05-25 18:51
Hi, thanks a lot for your issue ! I think this is a duplicate of #70 . We've had a report for it already

**Comment by guruprasaad123** [comment] 2020-05-26 03:28
> Hi, thanks a lot for your issue ! I think this is a duplicate of #70 . We've had a report for it already

Sorry please dont mind

**Closed** 2020-05-28 17:06 UTC
